language: r
cache: packages
pandoc: false
disable_homebrew: true

before_install:
  - git clone --depth=1 -b apache-arrow-0.14.0 https://github.com/apache/arrow.git
  - cd arrow/r

matrix:
  include:
  - os: linux
    r: release
  - os: linux
    r: devel
  - os: osx
    # CRAN is stuck on 10.11, xcode 8.2
    osx_image: xcode8
    # The MacTeX the job tries to install requires 10.12 or greater
    latex: false
    r: release
    # Add this env var so we can assert in the tests that the library is installed correctly
    env: TEST_R_WITH_ARROW=TRUE
