language: r
cache: packages
pandoc: false
disable_homebrew: true

before_install:
  - git clone --depth=1 -b apache-arrow-0.14.0 https://github.com/apache/arrow.git
  - cd arrow/r

matrix:
  include:
  - os: linux
    r: release
  - os: linux
    r: devel
  - os: osx
    osx_image: xcode10.2
    r: devel
    # Add this env var so we can assert in the tests that the library is installed correctly
    env: TEST_R_WITH_ARROW=TRUE
