# Copied from https://github.com/krlmlr/r-appveyor/blob/master/sample.appveyor.yml

environment:
  TEST_R_WITH_ARROW: TRUE

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  - git clone --depth=1 -b apache-arrow-0.14.0 https://github.com/apache/arrow.git
  - cd arrow/r
  - ps: Bootstrap

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: 'arrow\r\*.Rcheck\**\*.log'
    name: Logs

  - path: 'arrow\r\*.Rcheck\**\*.out'
    name: Logs

  - path: 'arrow\r\*.Rcheck\**\*.fail'
    name: Logs

  - path: 'arrow\r\*.Rcheck\**\*.Rout'
    name: Logs

  - path: 'arrow\r\*_*.tar.gz'
    name: Bits

  - path: 'arrow\r\*_*.zip'
    name: Bits
